### PR TITLE
Added support for Haskell Language

### PR DESCRIPTION
**Pull request by aravindgopall**
Added support for Haskell language.

Known issue:
- the method node doesn't contain the signature. Need to see if we have to merge these nodes based on the use case.

### CODE REVIEW

**Comment by fynnfluegge** [comment]
@aravindgopall Nice one, many thanks! I added `Haskell` support to the Readme ✅

**Comment by fynnfluegge** [comment]
@aravindgopall Are you fine if I add this PR also to https://github.com/fynnfluegge/codeqai ? Or by yourself if you like? 🙂

**Comment by aravindgopall** [comment]
@fynnfluegge Thanks for the quick review and merge. You can raise the PR for `codeqai`, Thank you.

**Comment by fynnfluegge** [comment]
@aravindgopall I have to thank! 🙂

**Pull request merged**
